[project]
name = "odoo-addons-oca-l10n-colombia"
version = "18.0.20260904.0"
dependencies = [
    "odoo-addon-l10n_co_check_vat==18.0.*",
    "odoo-addon-l10n_co_currency_rate_update==18.0.*",
    "odoo-addon-l10n_co_economic_activities==18.0.*",
    "odoo-addon-l10n_co_electronic_invoice==18.0.*",
    "odoo-addon-l10n_co_electronic_invoice_self==18.0.*",
    "odoo-addon-l10n_co_verification_digit==18.0.*",
    "odoo-addon-l10n_co_withholding==18.0.*",
    "odoo-addon-l10n_co_withholding_advance==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
